apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless-ngx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:tstuessi/homelab.git
    targetRevision: main
    path: infrastructure/paperless-ngx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
