apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-share-healthcheck
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - noperm
    - mfsymlinks
    - noserverino
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: pv-smb-share-healthcheck
    volumeAttributes:
      source: "//192.168.40.144/media"
    nodeStageSecretRef:
      name: smb-creds
      namespace: kube-system
