apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/v1.20.3/deploy/v1.20.3/rbac-csi-smb.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/v1.20.3/deploy/v1.20.3/csi-smb-driver.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/v1.20.3/deploy/v1.20.3/csi-smb-controller.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/v1.20.3/deploy/v1.20.3/csi-smb-node.yaml
  - pv-smb-share.yaml
