apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-share
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: pv-smb-share
  resources:
    requests:
      storage: 100Gi
