apiVersion: v1
kind: Service
metadata:
  name: paperless-ngx-app-svc
spec:
  selector:
    app: paperless-ngx
  ports:
    - port: 80
      targetPort: 8000
      name: webui
    - port: 81
      targetPort: 5555
      name: flower
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-ngx-app
spec:
  selector:
    matchLabels:
      app: paperless-ngx
  template:
    metadata:
      labels:
        app: paperless-ngx
    spec:
      containers:
        - name: paperless-ngx
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              memory: "2Gi"
              cpu: "2"
          env:
            - name: PAPERLESS_DBHOST
              valueFrom:
                secretKeyRef:
                  name: paperless-ngx-secrets
                  key: postgres_host
            - name: PAPERLESS_DBUSER
              valueFrom:
                secretKeyRef:
                  name: paperless-ngx-secrets
                  key: postgres_user
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: paperless-ngx-secrets
                  key: postgres_password
            - name: PAPERLESS_DBENGINE
              value: postgresql
            - name: PAPERLESS_REDIS
              value: redis://paperless-ngx-valkey-svc:6379
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: paperless-ngx-secrets
                  key: secret_key
            - name: PAPERLESS_TIME_ZONE
              value: America/Chicago
            - name: PAPERLESS_URL
              value: https://paperless.k8s.tstuessi.com
            - name: PAPERLESS_USE_X_FORWARD_HOST
              value: "true"
            - name: PAPERLESS_USE_X_FORWARD_PORT
              value: "true"
            - name: PAPERLESS_PROXY_SSL_HEADER
              value: '["HTTP_X_FORWARDED_PROTO", "https"]'
            - name: PAPERLESS_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: paperless-ngx-secrets
                  key: admin_user
            - name: PAPERLESS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paperless-ngx-secrets
                  key: admin_password
            - name: PAPERLESS_ENABLE_FLOWER
              value: "true"
          volumeMounts:
            - name: paperless-ngx-data
              mountPath: /usr/src/paperless/data
            - name: paperless-ngx-pv
              mountPath: /usr/src/paperless/media
              subPath: paperless/media
            - name: paperless-ngx-pv
              mountPath: /usr/src/paperless/trash
              subPath: paperless/trash
            - name: paperless-ngx-pv
              mountPath: /usr/src/paperless/consume
              subPath: paperless/consume
            - name: paperless-ngx-pv
              mountPath: /usr/src/paperless/export
              subPath: paperless/export
          ports:
            - containerPort: 8000
              name: webui
            - containerPort: 5555
              name: flower
          readinessProbe:
            httpGet:
              path: /
              port: 8000
              httpHeaders:
                - name: Host
                  value: paperless.k8s.tstuessi.com
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 60
      volumes:
        - name: paperless-ngx-pv
          persistentVolumeClaim:
            claimName: smb-share
        - name: paperless-ngx-data
          emptyDir: {}
