apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  labels:
    app: romm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: pv-smb-share
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: romm
  serviceName: romm
  replicas: 1
  template:
    metadata:
      labels:
        app: romm
    spec:
      containers:
        - name: romm-db
          image: mariadb:12.3.3
          ports:
            - containerPort: 3306
              name: web
          volumeMounts:
            - name: mariadb-pv
              mountPath: /var/lib/mysql
              subPath: romm/db
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: romm-mariadb-root-creds
                  key: password
            - name: MARIADB_DATABASE
              value: romm
      volumes:
        - name: mariadb-pv
          persistentVolumeClaim:
            claimName: mariadb-pvc
