apiVersion: apps/v1
kind: Deployment
metadata:
  name: romm-app
spec:
  selector:
    matchLabels:
      app: romm-app
  template:
    metadata:
      labels:
        app: romm-app
    spec:
      enableServiceLinks: false
      containers:
        - name: romm
          image: rommapp/romm:latest
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: romm-pv
              mountPath: /romm/library
              subPath: romm/library
            - name: romm-pv
              mountPath: /romm/assets
              subPath: romm/assets
            - name: romm-pv
              mountPath: /romm/config
              subPath: romm/config
            - name: romm-pv
              mountPath: /romm/resources
              subPath: romm/resources
            - name: redis-data
              mountPath: /redis-data
          env:
            - name: DB_HOST
              value: romm-db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: romm-mariadb-root-creds
                  key: db_user
            - name: DB_PASSWD
              valueFrom:
                secretKeyRef:
                  name: romm-mariadb-root-creds
                  key: db_passwd
            - name: DB_NAME
              value: romm
            - name: ROMM_AUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: romm-mariadb-root-creds
                  key: romm_auth_secret_key
            - name: HASHEOUS_API_ENABLED
              value: "true"
            - name: STEAMGRIDDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: romm-mariadb-root-creds
                  key: steamgriddb_api_key
      volumes:
        - name: romm-pv
          persistentVolumeClaim:
            claimName: smb-share
        - name: redis-data
          emptyDir: {}
